-- 0014: Enable RLS on the two tables 0013 added.
--
-- 0013 shipped `partners` and `invite_codes` without RLS. Every other table in
-- this database, all sixteen of them, since 0001, enables it. Supabase's
-- dashboard flagged the omission when 0013 was applied to production.
--
-- WHY THIS IS NOT COSMETIC. Supabase grants the `anon` and `authenticated`
-- roles privileges on everything in the `public` schema, so RLS is the only
-- thing standing between the project's anon key and the table. With it off,
-- both tables were readable AND writable by any holder of that key:
--
--   partners      insert a row with multiplier 5 and welcome_grant 5000, sign
--                 up through the code, mint points at will. Also read the
--                 partner list and the commercial notes on each deal.
--   invite_codes  read every user's referral code, or delete rows to break the
--                 collision guarantee 0013 exists to provide, or squat a code
--                 so a real user can never be assigned it.
--
-- Scope of the exposure, stated accurately: this app publishes no anon key.
-- There is no NEXT_PUBLIC_SUPABASE_ANON_KEY and no browser Supabase client, -- every query goes through a Next route holding the service role. So reaching
-- these tables required obtaining the anon key some other way, and it was not
-- readable straight out of the bundle. It is still worth closing: the project
-- URL is committed in src/lib/supabase-admin.ts, the REST endpoint is public,
-- and an anon key is designed to be publishable, so its confidentiality is not
-- a thing to build a guarantee on. RLS is the guarantee.
--
-- The convention here is RLS enabled with NO policies. That denies anon and
-- authenticated everything, which is correct because no browser ever touches
-- these tables: `partners` is read and written only through
-- `createSupabaseAdmin()` in the admin route and src/lib/partners.ts, and
-- `invite_codes` is never touched by application code at all, the triggers in
-- 0013 maintain it. The service role bypasses RLS, so every existing code path
-- is unaffected.
--
-- Idempotent.

alter table partners     enable row level security;
alter table invite_codes enable row level security;
